### ISSUE TITLE
rsync 2.6 does not have some options used in this gem

### ISSUE THREAD

**Issue by RobertAudi** [linyows/capistrano-withrsync#8]
The `--acls` and `--xattrs` options are used by default [here](https://github.com/linyows/capistrano-withrsync/blob/master/lib/capistrano/tasks/withrsync.rake#L15-L16).

However, those options are not available in version 2.6, which is what comes by default on Mac OS X (see [the rsync man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/rsync.1.html) from the Apple developer website). Those options were introduced in version 3 (see [the rsync version 3.0.6 man page](http://linux.die.net/man/1/rsync)). Version 3 is available on OS X from Homebrew.

**Comment by linyows** [comment]
That's right. Please change the options or get the latest by homebrew.

**Comment by RobertAudi** [comment]
Already did. But the README should be updated (required rsync version and default value for `rsync_options`).
